services:
  db:
    image: postgres:15
    container_name: nest-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nest']
      interval: 10s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile # сам Dockerfile внутри
    container_name: nest-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGHOST: db
      PGDATABASE: ${DB}
      PGPORT: 5432

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_URI: http://minio:9000

    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  db_data:
